[package]
name = "s3pm-support"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
http = "1"

aws-sigv4 = { version = "1.3", features = ["sign-http"] }
aws-credential-types = "1.2"
aws-smithy-runtime-api = "1.9"

constant_time_eq = "0.4"
time = { version = "0.3", features = ["macros", "parsing", "formatting"] }

