[package]
name = "s3pm-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
uuid = { version = "1", features = ["v4"] }
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

s3pm-admin = { path = "../s3pm-admin" }
s3pm-directory = { path = "../s3pm-directory" }

