cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = [
  "crates/s32p-directory",
  "crates/s32p-proxy",
  "crates/s32p-support",
  "crates/s32p-admin",
  "crates/s32p-ctl",
  "crates/s32p-gateway",
]

[workspace.package]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
authors = ["Robert Redl"]
description = "S3 to POSIX proxy and gateway"

[workspace.dependencies]
rustls = { version = "0.23", features = ["aws_lc_rs", "read_buf"] }
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }

[profile.perf]
rustflags = ["-C", "target-cpu=native"]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

