cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = [
  "crates/s3pm-directory",
  "crates/s3pm-proxy",
  "crates/s3pm-support",
  "crates/s3pm-admin",
  "crates/s3pm-ctl",
  "crates/s3pm-gateway",
]

[workspace.dependencies]
rustls = { version = "0.23", features = ["aws_lc_rs", "read_buf"] }

[profile.perf]
rustflags = ["-C", "target-cpu=native"]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

