[package]
name = "s32p-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
lustre = []

[dependencies]
mimalloc = { workspace = true }
anyhow = { workspace = true }
http = { workspace = true }
httpdate = { workspace = true }
bytes = { workspace = true }
crossbeam-queue = "0.3"
io-uring = "0.7"

hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = { workspace = true }
tokio-stream = "0.1"
futures-util = "0.3"

tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "sync", "io-util"] }
tokio-util = { version = "0.7", features = ["io"] }

aligned-buffer = "0.2"
libc = { workspace = true }
dashmap = "6"

base64 = "0.22"
serde_json = { workspace = true }
serde = { workspace = true }
quick-xml = { workspace = true }
xattr = "1"
mime_guess = "2"
url = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
time = { workspace = true }

s32p-support = { path = "../s32p-support" }

[build-dependencies]
bindgen = "0.72"
pkg-config = "0.3"

