[package]
name = "s32p-directory"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "rt-multi-thread", "macros"] }
libc = { workspace = true }
s32p-support = { path = "../s32p-support" }

# OpenBao/Vault HTTP API
reqwest = { workspace = true }
serde_json = { workspace = true }

