[package]
name = "s3pm-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }

# We'll use reqwest directly so we don't depend on undocumented/unstable higher-level helpers.
reqwest = { version = "0.12", features = ["json"] }

uuid = { version = "1", features = ["v4"] }

tracing = "0.1"

s3pm-directory = { path = "../s3pm-directory" }

