#![cfg(all(feature = "lustre", target_os = "linux"))]

use anyhow::{anyhow, Result};
use std::os::unix::io::RawFd;

// Bindings generated by build.rs from <lustre/lustreapi.h>.
pub mod bindings {
    #![allow(
        non_camel_case_types,
        non_upper_case_globals,
        non_snake_case,
        dead_code,
        clippy::all
    )]

    include!(concat!(env!("OUT_DIR"), "/lustre_bindings.rs"));
}

use bindings::{
    llapi_lu_ladvise, 
    llapi_ladvise, 
    lu_ladvise_type::{self, LU_LADVISE_LOCKAHEAD, LU_LADVISE_LOCKNOEXPAND, LU_LADVISE_WILLREAD}, 
    ladvise_flag::LF_ASYNC
};

/// Lockahead mode values used by LL_IOC_LADVISE / LU_LADVISE_LOCKAHEAD.
///
/// Commonly: READ_USER=1, WRITE_USER=2 (see ROMIO/MPICH lockahead_ladvise patch).
#[repr(u16)]
pub enum LockaheadMode {
    ReadUser = 1,
    WriteUser = 2,
}

fn ladvise_range(fd: RawFd, advice: lu_ladvise_type, start: u64, len: u64, value1: u64) -> Result<()> {
    if len == 0 {
        return Ok(());
    }

    let end = start
        .checked_add(len - 1)
        .ok_or_else(|| anyhow!("ladvise range overflow: start={start} len={len}"))?;

    let mut adv: llapi_lu_ladvise = unsafe { std::mem::zeroed() };
    adv.lla_advice = advice as _;
    adv.lla_start = start as _;
    adv.lla_end = end as _;
    adv.lla_value1 = value1 as _;
    adv.lla_value2 = 0;

    // prrform will read async
    let flag = match advice {
        LU_LADVISE_WILLREAD => LF_ASYNC as u64,
        _ => 0,
    };


    let rc = unsafe { llapi_ladvise(fd as i32, flag, 1, &mut adv as *mut _) };
    if rc == 0 {
        Ok(())
    } else {
        Err(anyhow!("llapi_ladvise({advice:?}) failed: {}", std::io::Error::last_os_error()))
    }
}

/// Best-effort: prevent Lustre from expanding extent locks beyond [start, start+len).
pub fn advise_locknoexpand(fd: RawFd, start: u64, len: u64) {
    // value1/value2 are unused for LOCKNOEXPAND; pass 0.
    if let Err(e) = ladvise_range(fd, LU_LADVISE_LOCKNOEXPAND, start, len, 0) {
        tracing::debug!("locknoexpand failed: {e}");
    } else {
        tracing::debug!("locknoexpand succeeded: start={start}, len={len}");
    }
}

/// Best-effort: lockahead for writes over [start, start+len).
pub fn advise_lockahead_write(fd: RawFd, start: u64, len: u64) {
    if let Err(e) = ladvise_range(fd, LU_LADVISE_LOCKAHEAD, start, len, LockaheadMode::WriteUser as u64) {
        tracing::debug!("lockahead write failed: {e}");
    } else {
        tracing::debug!("lockahead write succeeded: start={start}, len={len}");
    }
}

/// Best-effort: tell Lustre we will read [start, start+len).
pub fn advise_willread(fd: RawFd, start: u64, len: u64) {
    // value1/value2 are unused for WILLREAD; pass 0.
    if let Err(e) = ladvise_range(fd, LU_LADVISE_WILLREAD, start, len, 0) {
        tracing::debug!("willread failed: {e}");
    } else {
        tracing::debug!("willread succeeded: start={start}, len={len}");
    }
}

